### DISCUSSION TITLE
Hosting Documentation in Netlify or Vercel

### DISCUSSION THREAD

**Discussion by yezz123** [adriangb/xpresso#80] [Ideas]
Hey @adriangb I have i little enhancement on the way how you could improve the CI/CD of Xpresso, the same thing I try it before in AuthX, the same thing we use MKdocs in Documentation that's why you could build it and generate HTML main file and some assets files `.js` & `.css`, that's why you could host it in Netlify using `jsmrcaga/action-netlify-deploy@v1.1.0`  here is the CI File i use it in authx to host it in Netlify:

```yaml
name: Build Docs
on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-docs
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: python3.9 -m pip install flit
      - name: Install docs extras
        if: steps.cache.outputs.cache-hit != 'true'
        run: python3.9 -m flit install --deps production --extras docs
      - name: Build docs
        run: mkdocs build -d build

      - name: Deploy docs
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
```
